---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helloworld
  namespace: helloworld
spec:
  interval: 30s
  url: https://github.com/airwalk-mj/tf-demo-flux
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: helloworld
spec:
  interval: 1m
  approvePlan: auto
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: helloworld
  writeOutputsToSecret:
    name: helloworld-output

# To read TF outputs (saved as as a secret)
# kubectl -n flux-system get secret helloworld-output -o jsonpath='{.data.message}' | base64 --decode